name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses GitHub's hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build site
        run: echo "Building site..."  # Replace with actual build commands if needed

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Adjust if necessary

      - name: Deploy
        uses: actions/deploy-pages@v1
